name: CI
on:
  - pull_request
  - push
jobs:
  phpunit:
    name: "PHPUnit (PHP: ${{ matrix.php-versions }})"
    runs-on: ubuntu-latest
    env:
      APP_CONNECTION: "pdo-sqlite:////${{ github.workspace }}/cache/app.db"
    strategy:
      matrix:
        php-versions:
          - 8.4
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Composer install
        run: composer install --no-interaction --no-ansi --no-progress

      - name: Setup SQLite Cache Directory
        run: |
          mkdir -p ${{ github.workspace }}/cache
          touch ${{ github.workspace }}/cache/app.db
          chmod -R 777 ${{ github.workspace }}/cache

      - name: Start FrankenPHP via Docker
        run: |
          docker run -d \
            --name frankenphp-server \
            --net=host \
            -v ${{ github.workspace }}:/app \
            -w /app \
            -e APP_CONNECTION="pdo-sqlite:////app/cache/app.db" \
            dunglas/frankenphp frankenphp run --config Caddyfile

      - name: Wait for FrankenPHP
        run: |
          for i in {1..10}; do
            if curl -s http://127.0.0.1:8080 > /dev/null; then
              echo "FrankenPHP is up!"
              exit 0
            fi
            echo "Waiting for port 8080... ($i/10)"
            sleep 1
          done
          
          echo "FrankenPHP failed to start! Dumping log:"
          docker logs frankenphp-server
          exit 1

      - name: Run PHPUnit
        run: SEND=external vendor/bin/phpunit

      - name: Print Logs on Failure
        if: failure()
        run: docker logs frankenphp-server